project_id = "trmcgpjsweacadqoadlh"

[functions.generate-memory-suggestions]
verify_jwt = false

[functions.add-video]
verify_jwt = false

[functions.ai-process]
verify_jwt = false

[functions.generate-key-points]
verify_jwt = false

[functions.ai-clarify-task]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.re-segment-transcript]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
