// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-videos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-videos.ts
var list_videos_default = defineTool({
  name: "list_videos",
  title: "List videos",
  description: "List the signed-in user's saved videos in Memory Link, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of videos to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("videos").select("id, title, youtube_url, status, duration_seconds, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { videos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-memory-items.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_memory_items_default = defineTool2({
  name: "list_memory_items",
  title: "List memory items",
  description: "List the signed-in user's saved memory items (summaries and key points captured from videos).",
  inputSchema: {
    video_id: z2.string().uuid().optional().describe("Only return memory items for this video id."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of items to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ video_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("remember_items").select("id, summary, key_points, video_id, timestamp_seconds, review_schedule, created_at").is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (video_id) query = query.eq("video_id", video_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { memory_items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool3({
  name: "list_tasks",
  title: "List to-dos",
  description: "List the signed-in user's to-dos in Memory Link, optionally filtered by status.",
  inputSchema: {
    status: z3.enum(["pending", "in_progress", "completed"]).optional().describe("Filter by task status."),
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of tasks to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tasks").select("id, title, description, status, due_date, video_id, order_index, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_task_default = defineTool4({
  name: "create_task",
  title: "Create to-do",
  description: "Create a new to-do for the signed-in user in Memory Link.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Short title of the to-do."),
    description: z4.string().trim().optional().describe("Optional longer description."),
    due_date: z4.string().optional().describe("Optional due date as an ISO 8601 date or timestamp.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      due_date: due_date ?? null,
      timestamp_seconds: 0,
      source_type: "manual",
      status: "pending"
    }).select("id, title, description, status, due_date, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { task: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/update-task-status.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var update_task_status_default = defineTool5({
  name: "update_task_status",
  title: "Update to-do status",
  description: "Update the status of one of the signed-in user's to-dos (pending, in_progress, completed).",
  inputSchema: {
    task_id: z5.string().uuid().describe("Id of the task to update."),
    status: z5.enum(["pending", "in_progress", "completed"]).describe("New status for the task.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").update({ status }).eq("id", task_id).select("id, title, status, due_date");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "Task not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { task: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "trmcgpjsweacadqoadlh";
var mcp_default = defineMcp({
  name: "memory-link-master",
  title: "Memory Link Master",
  version: "0.1.0",
  instructions: "Tools for Memory Link, an app that turns videos into memory items and to-dos. Use `list_videos` to see saved videos, `list_memory_items` for captured summaries and key points, and `list_tasks` / `create_task` / `update_task_status` to manage the user's to-dos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_videos_default, list_memory_items_default, list_tasks_default, create_task_default, update_task_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
